import type { Metadata } from "next";
import PrintButton from "@/components/sub/print-button";

export const metadata: Metadata = {
  title: "Terms & Conditions | BLOCKMEN",
  description: "Terms and Conditions for using BLOCKMEN platform and services.",
};

export default function TermsPage() {
  return (
    <main className="min-h-screen w-full pt-24 pb-16 px-4">
      <div className="max-w-3xl mx-auto">
        <div className="flex items-start justify-between gap-4 mb-2">
          <h1 className="text-3xl md:text-4xl font-bold text-white">
            Terms &amp; Conditions
          </h1>
          <PrintButton />
        </div>
        <p className="text-gray-400 mb-10 text-sm">Last updated: May 2026</p>

        <div className="space-y-8 text-gray-300 leading-relaxed">
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules thereunder as applicable, and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with the provisions of Rule
            3(1) of the Information Technology (Intermediaries guidelines)
            regulations, and pertains to the privacy policy and Terms of Use for
            access or usage of the domain name{" "}
            <span className="text-purple-400 font-medium">
              THEBLOCKMEN.COM
            </span>{" "}
            (hereinafter referred to as &apos;Platform&apos;). The Platform is
            owned by{" "}
            <span className="text-purple-400 font-medium">BLOCKMEN</span>, a
            company incorporated under the Companies Act, 1956, with its
            registered office at A-1004 Rama Metro Life Maxima, Tathawade,
            Pune.
          </p>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Acceptance of Terms
            </h2>
            <p>
              Your use of the Platform and services and tools are governed by
              the following terms and conditions. If You transact on the
              Platform, You shall be subject to the policies applicable to the
              Platform for such transaction. By mere use of the Platform, You
              shall be contracting with the Platform Owner and these terms and
              conditions including the policies constitute Your binding
              obligations with the Platform Owner.
            </p>
            <p className="mt-3 font-medium text-white/80">
              ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES
              YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS
              OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE
              PROCEEDING.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Terms of Use
            </h2>
            <ol className="list-decimal list-outside ml-5 space-y-3">
              <li>
                To access and use the Services, you agree to provide true,
                accurate and complete information to us during and after
                registration, and you shall be responsible for all acts done
                through the use of your registered account on the Platform.
              </li>
              <li>
                Neither we nor any third parties provide any warranty or
                guarantee as to the accuracy, timeliness, performance,
                completeness or suitability of the information and materials
                offered on this website or through the Services, for any
                specific purpose. You acknowledge that such information and
                materials may contain inaccuracies or errors and we expressly
                exclude liability for any such inaccuracies or errors to the
                fullest extent permitted by law.
              </li>
              <li>
                Your use of our Services and the Platform is solely and entirely
                at your own risk and discretion for which we shall not be liable
                to you in any manner. You are required to independently assess
                and ensure that the Services meet your requirements.
              </li>
              <li>
                The contents of the Platform and the Services are proprietary to
                us and are licensed to us. You will not have any authority to
                claim any intellectual property rights, title, or interest in
                its contents. The contents include and are not limited to the
                design, layout, look and graphics.
              </li>
              <li>
                You acknowledge that unauthorized use of the Platform and/or the
                Services may lead to action against you as per these Terms of
                Use and/or applicable laws.
              </li>
              <li>
                You agree to pay us the charges associated with availing the
                Services.
              </li>
              <li>
                You agree not to use the Platform and/or Services for any
                purpose that is unlawful, illegal or forbidden by these Terms,
                or Indian or local laws that might apply to you.
              </li>
              <li>
                You agree and acknowledge that the website and the Services may
                contain links to other third-party websites. On accessing these
                links, you will be governed by the terms of use, privacy policy
                and such other policies of such third-party websites.
              </li>
              <li>
                You understand that upon initiating a transaction for availing
                the Services you are entering into a legally binding and
                enforceable contract with the Platform Owner for the Services.
              </li>
              <li>
                You shall indemnify and hold harmless the Platform Owner, its
                affiliates, group companies (as applicable), their respective
                officers, directors, agents, and employees from any claim,
                demand, or actions including reasonable attorney&apos;s fees,
                made by any third party or penalty imposed due to or arising out
                of Your breach of these Terms of Use, Privacy Policy and other
                Policies, or Your violation of any law, rules or regulations or
                the rights of a third party.
              </li>
              <li>
                Notwithstanding anything contained in these Terms of Use, the
                parties shall not be liable for any failure to perform an
                obligation under these Terms if performance is prevented or
                delayed by a force majeure event.
              </li>
              <li>
                These Terms and any dispute or claim relating to it, or its
                enforceability, shall be governed by and construed in accordance
                with the laws of India.
              </li>
              <li>
                All disputes arising out of or in connection with these Terms
                shall be subject to the exclusive jurisdiction of the competent
                courts in India.
              </li>
            </ol>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Modifications
            </h2>
            <p>
              These Terms of Use can be modified at any time without assigning
              any reason. It is your responsibility to periodically review these
              Terms of Use to stay informed of updates.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Governing Law
            </h2>
            <p>
              These Terms of Use and any dispute or claim arising out of or in
              connection with them, including non-contractual disputes or claims,
              shall be governed by and construed in accordance with the laws of
              India. The Information Technology Act, 2000, the Consumer
              Protection Act, 2019, and other applicable Indian statutes shall
              apply where relevant.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Dispute Resolution
            </h2>
            <p>
              In the event of any dispute, controversy, or claim arising out of
              or relating to these Terms, or the breach, termination, or
              validity thereof, the parties shall first attempt to resolve the
              matter through good-faith negotiation. Either party may initiate
              this process by sending written notice to the other party.
            </p>
            <p className="mt-3">
              If the dispute is not resolved within{" "}
              <strong className="text-white">30 days</strong> of such written
              notice, it shall be referred to and finally resolved by
              arbitration in accordance with the Arbitration and Conciliation
              Act, 1996 (India). The seat of arbitration shall be Pune,
              Maharashtra, India. The language of arbitration shall be English.
            </p>
            <p className="mt-3">
              Nothing in this clause shall prevent either party from seeking
              interim or injunctive relief from a court of competent
              jurisdiction. Subject to the arbitration clause above, all
              disputes shall be subject to the exclusive jurisdiction of the
              courts in Pune, Maharashtra, India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white mb-3">
              Contact Us
            </h2>
            <div className="p-4 rounded-xl border border-white/10 bg-white/5 space-y-1 text-sm">
              <p><strong className="text-white">Business Name:</strong> BLOCKMEN</p>
              <p>
                <strong className="text-white">Email:</strong>{" "}
                <a
                  href="mailto:talent@theblockmen.com"
                  className="text-purple-400 hover:text-purple-300 underline transition-colors"
                >
                  talent@theblockmen.com
                </a>
              </p>
              <p><strong className="text-white">Website:</strong> www.theblockmen.com</p>
              <p>
                <strong className="text-white">Address:</strong> A-1004, Rama
                Metro Life Maxima, Tathawade, Pune – 411033, Maharashtra, India
              </p>
            </div>
          </section>
        </div>
      </div>
    </main>
  );
}
